from featureSelector import *

dictionary = {
                1 : featureSelector.zeroFeature,
                2 : featureSelector.zeroFeature,
                3 : featureSelector.zeroFeature,
                4 : featureSelector.zeroFeature,
                5 : featureSelector.zeroFeature,
                6 : featureSelector.zeroFeature,
                7 : featureSelector.zeroFeature,
                8 : featureSelector.zeroFeature,
                9 : featureSelector.zeroFeature,
                10 : featureSelector.zeroFeature,
                11 : featureSelector.zeroFeature,
                12 : featureSelector.zeroFeature,
                13 : featureSelector.zeroFeature,
                14 : featureSelector.zeroFeature,
                15 : featureSelector.zeroFeature,
                16 : featureSelector.zeroFeature,
                17 : featureSelector.zeroFeature,
                18 : featureSelector.zeroFeature,
                19 : featureSelector.zeroFeature,
                20 : featureSelector.zeroFeature,
                21 : featureSelector.zeroFeature,
                22 : featureSelector.zeroFeature,
                23 : featureSelector.iframeTag,
                24 : featureSelector.zeroFeature,
                25 : featureSelector.zeroFeature,
                26 : featureSelector.zeroFeature,
                27 : featureSelector.zeroFeature,
                28 : featureSelector.zeroFeature,
                29 : featureSelector.zeroFeature,
                30 : featureSelector.zeroFeature,
            }
